### ISSUE TITLE
error in Reward_BIC

### ISSUE THREAD

**Issue by pckennethma** [huawei-noah/trustworthyAI#44]
Hello,

I am trying to use Causal Disocvery RL on bnlearn benchmarks. It throws the following errors on some datasets (e.g., hailfinder, water) after some iterations. 

```python
Traceback (most recent call last):
  File "main.py", line 344, in <module>
    main()
  File "main.py", line 180, in main
    reward_feed = callreward.cal_rewards(graphs_feed, lambda1, lambda2)
  File "/home/v-pingma/Causal_Discovery_RL/src/rewards/Reward_BIC.py", line 45, in cal_rewards
    reward_ = self.calculate_reward_single_graph(graphi, lambda1, lambda2)
  File "/home/v-pingma/Causal_Discovery_RL/src/rewards/Reward_BIC.py", line 117, in calculate_reward_single_graph
    y_err = self.calculate_yerr(X_train, y_train)
  File "/home/v-pingma/Causal_Discovery_RL/src/rewards/Reward_BIC.py", line 55, in calculate_yerr
    return self.calculate_LR(X_train, y_train)
  File "/home/v-pingma/Causal_Discovery_RL/src/rewards/Reward_BIC.py", line 69, in calculate_LR
    theta = np.linalg.solve(XtX, Xty)
  File "<__array_function__ internals>", line 6, in solve
  File "/anaconda/envs/cdrl/lib/python3.6/site-packages/numpy/linalg/linalg.py", line 394, in solve
    r = gufunc(a, b, signature=signature, extobj=extobj)
  File "/anaconda/envs/cdrl/lib/python3.6/site-packages/numpy/linalg/linalg.py", line 88, in _raise_linalgerror_singular
    raise LinAlgError("Singular matrix")
numpy.linalg.LinAlgError: Singular matrix
```

**Comment by shaido987** [comment]
Hello,

[`np.linalg.solve`](https://numpy.org/doc/stable/reference/generated/numpy.linalg.solve.html) expects a full-rank matrix to run which is not the case here. You can modify the code to compute the least-squares directly using [`np.linalg.lstsq`](https://numpy.org/doc/stable/reference/generated/numpy.linalg.lstsq.html#numpy.linalg.lstsq) instead. Something like:

```python
def calculate_LR(self, X_train, y_train):
    X = np.hstack((X_train, self.ones))
    XtX = X.T.dot(X)
    Xty = X.T.dot(y_train)
    theta = np.linalg.lstsq(XtX, Xty, rcond=None)[0]
    y_err = X.dot(theta) - y_train
    return y_err
```

This will give very similar results to `np.linalg.solve` and should make the datasets possible to run.

Whether the matrix being singular has any other issues or impact on the final results, my colleague should be able to answer far better than me.

**Comment by pckennethma** [comment]
thanks a lot. it works.
