### ISSUE TITLE
运行主函数，代码未改动，但报出代码有问题

### ISSUE THREAD

**Issue by cczhangy** [huawei-noah/trustworthyAI#58]

**Comment by shaido987** [comment]
Hello, can you add the code/command you used here to reproduce this error?

**Comment by cczhangy** [comment]
您好，我复现《CAUSAL DISCOVERY WITH REINFORCEMENT LEARNING》这篇论文的代码，运行的是下面这个实验




其中的一些参数已经在源代码中改过，执行结果如下图所示



------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "huawei-noah/trustworthyAI"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年4月7日(星期四) 下午2:15
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [huawei-noah/trustworthyAI] 运行主函数，代码未改动，但报出代码有问题：UnboundLocalError: local variable 'lambda1_update_add' referenced before assignment (Issue #58)





 
Hello, can you add the code/command you used here to reproduce this error?

**Comment by shaido987** [comment]
The images seems to have been lost somehow. Maybe you can add them as text or through the website?

**Comment by cczhangy** [comment]
执行的实验是：# exp1: RL-BIC, assuming different noise variances
运行的结果如下：
2022-04-07 15:45:10,887 INFO - __main__ - Finished creating training dataset, actor model and reward class
2022-04-07 15:45:10,968 INFO - __main__ - Starting session...
2022-04-07 15:45:12,584 INFO - __main__ - Shape of actor.input: [64 12 64]
2022-04-07 15:45:14,335 INFO - __main__ - Starting training.
2022-04-07 15:45:21,049 INFO - __main__ - [iter 1] reward_batch: -inf, max_reward: -3.0, max_reward_batch: -inf
2022-04-07 15:46:17,115 INFO - __main__ - Model saved in file: output/2022-04-07_15-45-03-259/model/tmp.ckpt-400
2022-04-07 15:46:28,666 INFO - __main__ - [iter 500] reward_batch: -inf, max_reward: -3.0, max_reward_batch: -inf
2022-04-07 15:47:05,704 INFO - __main__ - Model saved in file: output/2022-04-07_15-45-03-259/model/tmp.ckpt-800
2022-04-07 15:47:30,347 CRITICAL - helpers.log_helper - Unhandled exception
Traceback (most recent call last):
&nbsp; File "D:/code/trustworthyAI-master/Causal_Structure_Learning/Causal_Discovery_RL/src/main.py", line 314, in <module&gt;
&nbsp; &nbsp; main()
&nbsp; File "D:/code/trustworthyAI-master/Causal_Structure_Learning/Causal_Discovery_RL/src/main.py", line 270, in main
&nbsp; &nbsp; lambda1 = min(lambda1+lambda1_update_add, lambda1_upper)
UnboundLocalError: local variable 'lambda1_update_add' referenced before assignment





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "huawei-noah/trustworthyAI"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年4月7日(星期四) 下午4:25
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [huawei-noah/trustworthyAI] 运行主函数，代码未改动，但报出代码有问题：UnboundLocalError: local variable 'lambda1_update_add' referenced before assignment (Issue #58)





 
The images seems to have been lost somehow. Maybe you can add them as text or through the website?

**Comment by shaido987** [comment]
Can you confirm if `the --lambda_flag_default` flag is used when running? 

Using this flag then `config.lambda_flag_default` on [line 80](
https://github.com/huawei-noah/trustworthyAI/blob/934a924a7849e9f6abf0f561f59a1211dca435ad/Causal_Structure_Learning/Causal_Discovery_RL/src/main.py#L80) should be true which sets the `lambda1_update_add` variable to `1` ([on line 86](https://github.com/huawei-noah/trustworthyAI/blob/934a924a7849e9f6abf0f561f59a1211dca435ad/Causal_Structure_Learning/Causal_Discovery_RL/src/main.py#L86)).

**Comment by cczhangy** [comment]
Thank you very much, the program can run normally, thank you again！


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "huawei-noah/trustworthyAI"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年4月7日(星期四) 下午5:04
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [huawei-noah/trustworthyAI] 运行主函数，代码未改动，但报出代码有问题：UnboundLocalError: local variable 'lambda1_update_add' referenced before assignment (Issue #58)





 
Can you confirm if the --lambda_flag_default flag is used when running?
 
Using this flag then config.lambda_flag_default on line 80 should be true which sets the lambda1_update_add variable to 1 (on line 86).
