### ISSUE TITLE
CAUSAL DISCOVERY WITH REINFORCEMENT LEARNING

### ISSUE THREAD

**Issue by cczhangy** [huawei-noah/trustworthyAI#62]
On the synthetic dataset, there is no error in the execution result. On the sachs dataset, the code error is as follows:
Traceback (most recent call last):
  File "main.py", line 314, in <module>
    main()
  File "main.py", line 284, in main
    graph_batch_pruned = np.transpose(pruning_cam(training_set.inputdata, np.array(graph_batch).T))
  File "D:\code\trustworthyAI-master\Causal_Structure_Learning\Causal_Discovery_RL\src\helpers\cam_with_pruning_cam.py", line 129, in pruning_cam
    X2 = numpy2ri.py2rpy(XX)
AttributeError: module 'rpy2.robjects.numpy2ri' has no attribute 'py2rpy'
Please help me how to solve this problem？

**Comment by shaido987** [comment]
What version of rpy2 do you have installed? Is it 3.1.0 (as in the requirements.txt file)?

**Comment by cczhangy** [comment]
Hello, I have the real adjacency matrix of the sachs dataset in your experiment log: [[0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
  [0. 0. 0. 1. 1. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [1. 1. 0. 0. 0. 1. 1. 0. 0. 1. 1.]
  [1. 1. 0. 0. 0. 0. 0. 1. 0. 1. 1.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]], but the result of my execution shd is different from the result in the log, what may be the problem? Also, does the real matrix of sachs look like this, I deduced it from that network a bit differently?

**Comment by shaido987** [comment]
The experiments are run without any seed so there can be some differences in the results. If there is a large difference, first make sure that the run command is the same, i.e.:

```
python main.py --max_length 11 \
                --data_size 853 \
                --score_type BIC \
                --reg_type GPR \
                --read_data  \
                --use_bias \
                --bias_initial_value -10 \
                --normalize \
                --data_path input_data_path/sachs \
                --lambda_flag_default \
                --nb_epoch 20000 \
                --input_dimension 128 \
                --lambda_iter_num 1000
```

You could also try to run one of the experiments on the synthetic data to see if the result matches.

For the adjacency matrix, since it's from the training logs then it should be the same.

**Comment by shaido987** [comment]
Hello @cczhangy ,

1. Make sure that the installed rpy2 version is the correct one (3.1.0) as there have been some changes to the library.
2. When trying the synthetic data (i.e., with 30 nodes), you need to change the `--reg_type` to be `GPR` to use the CAM pruning. The other regularization types do not use the part of the code that throws the error. It looks like this: https://github.com/huawei-noah/trustworthyAI/blob/317cff04b68ee9b4831cf0d00489c2a4ded3344b/research/Causal%20Discovery%20with%20RL/src/main.py#L277-L284
